---
---
# Source: spark-hs/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-hs
  labels:
    app.kubernetes.io/name: spark-hs
    app.kubernetes.io/instance: spark-history-server
    app.kubernetes.io/managed-by: Kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-hs
      app.kubernetes.io/instance: spark-history-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-hs
        app.kubernetes.io/instance: spark-history-server
    spec:
      serviceAccountName: spark
      securityContext:
        {}
      containers:
        - name: spark-hs
          securityContext:
            null
          image: "quay.io/tcarland/spark:v3.2.1-callisto-2202.06"
          imagePullPolicy: IfNotPresent
          args: [
              "/bin/sh",
              "-c",
              "/opt/spark/sbin/start-history-server.sh"
          ]
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "false"
            - name: SPARK_HISTORY_OPTS
              value: "-Dspark.history.fs.logDirectory=s3a://spark/spark-logs \
                      -Dspark.hadoop.fs.s3a.endpoint=http://10.92.9.186:80 \
                      -Dspark.hadoop.fs.s3a.access.key=Vw9sl0xmZPZ4zKxzS7P6 \
                      -Dspark.hadoop.fs.s3a.secret.key=wUW5IyjDRugVLdCOEZhGeDaU8ws6NIpCbn6OBHKg \
                      -Dspark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem \
                      -Dcom.amazonaws.sdk.disableCertChecking=false"
            - name: SPARK_CONF_DIR
              value: /opt/spark/conf
          volumeMounts:
            - name: config-volume
              mountPath: /opt/spark/conf/spark-defaults.conf
              subPath: spark-defaults.conf
            - name: keystore-volume
              mountPath: /mnt/secrets
              readOnly: true
          ports:
            - name: http
              containerPort: 18080
              protocol: TCP
          resources:
            {}
      volumes:
        - name: config-volume
          configMap:
            name: spark-hs-config
        - name: keystore-volume
          secret:
            secretName: spark-hs-keystore
            items:
            - key: keystore.jks
              path: keystore.jks
            - key: truststore.jks
              path: truststore.jks
