---
apiVersion: v1
kind: Service
metadata:
  name: spark-hs
  namespace: spark
  labels:
    app.kubernetes.io/name: spark-hs
    app.kubernetes.io/instance: spark-history-server
    app.kubernetes.io/managed-by: Kustomize
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 18080
      targetPort: 18080
  selector:
    app.kubernetes.io/name: spark-hs
    app.kubernetes.io/instance: spark-history-server
