---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark
  labels:
    app.kubernetes.io/name: spark-hs
    app.kubernetes.io/instance: spark-history-server
    app.kubernetes.io/managed-by: Kustomize