#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
ARG java_image_tag=21

FROM azul/zulu-openjdk:${java_image_tag}
LABEL org.opencontainers.image.authors="Apache Spark project <dev@spark.apache.org>"
LABEL org.opencontainers.image.licenses="Apache-2.0"
LABEL org.opencontainers.image.ref.name="Apache Spark Scala/Java Image"
LABEL org.opencontainers.image.version="io"

ARG hive_uri=https://archive.apache.org/dist/hive
ARG hive_version=3.1.3
ARG spark_uid=185

RUN set -ex && \
    apt-get update && \
    ln -s /lib /lib64 && \
    apt install -y bash coreutils curl tini libc6 libpam-modules krb5-user libnss3 procps net-tools logrotate libssl-dev && \
    mkdir -p /opt/spark /opt/spark/logs /opt/spark/work-dir && \
    touch /opt/spark/RELEASE && \
    rm /bin/sh && \
    ln -sv /bin/bash /bin/sh && \
    useradd -u ${spark_uid} -m spark && \
    echo "auth required pam_wheel.so use_uid" >> /etc/pam.d/su && \
    chgrp root /etc/passwd && chmod ug+rw /etc/passwd && \
    rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/*

COPY jars /opt/spark/jars
COPY hive-jackso[n] /opt/spark/hive-jackson
COPY RELEAS[E] /opt/spark/RELEASE
COPY bin /opt/spark/bin
COPY sbin /opt/spark/sbin
COPY kubernetes/dockerfiles/spark/entrypoint.sh /opt/
COPY kubernetes/dockerfiles/spark/decom.sh /opt/
#COPY examples /opt/spark/examples
#RUN ln -s $(basename /opt/spark/examples/jars/spark-examples_*.jar) /opt/spark/examples/jars/spark-examples.jar
COPY kubernetes/tests /opt/spark/tests
COPY data /opt/spark/data
COPY ca.cr[t] /opt/spark/ca.crt

RUN curl -L ${hive_uri}/hive-${hive_version}/apache-hive-${hive_version}-bin.tar.gz \
	| tar xvz -C /opt/ \
	&& ln -s /opt/apache-hive-${hive_version}-bin /opt/hive
	
RUN if [ -f /opt/spark/ca.crt ]; then \
        cp /opt/spark/ca.crt /usr/local/share/ca-certificates/tdh-ca.crt && \
        update-ca-certificates && \
        keytool -import -trustcacerts -cacerts -storepass changeit -noprompt -alias tdh-ca -file /usr/local/share/ca-certificates/tdh-ca.crt; \
    fi

ENV SPARK_HOME=/opt/spark

WORKDIR /opt/spark/work-dir
RUN chown spark:spark /opt/spark/work-dir /opt/spark/logs && \
    chmod g+w /opt/spark/work-dir /opt/spark/logs && \
    chmod a+x /opt/decom.sh

ENTRYPOINT [ "/opt/entrypoint.sh" ]

USER ${spark_uid}
