---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-history-server
  namespace: argocd
spec:
  destination:
    namespace: spark
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
       - name: s3.endpoint
         value: "$S3_ENDPOINT"
       - name: s3.accessKey
         value: "$S3_ACCESS_KEY"
       - name: s3.secretKey
         value: "$S3_SECRET_KEY"
       - name: s3.logDirectory
         value: "s3a://spark/spark-logs"
       - name: service.type
         value: "LoadBalancer"
       - name: ssl.keystoreSecretName
         value: "spark-hs-keystore"
       - name: ssl.keystorePassword
         value: "$KEYSTORE_PASSWD"
       - name: ssl.truststoreSecretName
         value: "spark-hs-truststore"
       - name: ssl.truststorePassword
         value: "$TRUSTSTORE_PASSWD"
    chart: spark-hs
    repoURL: https://tcarland.github.io/spark-hs-chart/
    targetRevision: 1.6.2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
