{{- if .Values.ssl.keystoreFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-hs.name" . }}-keystore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-hs.labels" . | nindent 4 }}
data:
  keystore.jks: |-
    "{{ .Files.Get .Values.ssl.keystoreFile | b64enc }}"
{{- end }}
