---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-hs.name" . }}-keystore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-hs.labels" . | nindent 4 }}
data:
  keystore.jks: "{{ .Values.secrets.keystoreBase64 }}"
  truststore.jks: "{{ .Values.secrets.truststoreBase64 }}"