apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-hs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-hs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    {{- include "spark-hs.selectorLabels" . | nindent 4 }}
