apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-hs.name" . }}
  labels:
    {{- include "spark-hs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "spark-hs.selectorLabels" . | nindent 4 }}
