{{- if .Values.ssl.truststoreFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-hs.name" . }}-truststore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-hs.labels" . | nindent 4 }}
data:
  truststore.jks: |-
    "{{ .Files.Get .Values.ssl.truststoreFile | b64enc }}"
{{- end }}
